version: '3.9'
services:
  flask-server:
    image: python:3.8
    container_name: flask_server
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "443:443"
    command: sh -c "pip install flask pyopenssl && python server.py"

  fixed-app:
    image: python:3.8
    container_name: fixed_urllib3
    working_dir: /app
    volumes:
      - ./app:/app
    depends_on:
      - flask-server
    command: sh -c "pip install urllib3==1.26.16 && python fixed.py"
