version: '3'

services:
  https-server:
    image: python:3.8-slim
    container_name: http_server
    volumes:
      - .:/app  # Mount the current directory
    working_dir: /app
    command: sh -c "python3 https_server.py"  # Run the HTTPS server

  urllib3-exploit:
    image: python:3.8-slim
    container_name: urllib3-exploit
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "pip install urllib3==1.26.0 && python3 exploit.py"
    depends_on:
      - https-server  # Ensure https-server starts first

