version: '3'
services:
  flask-vulnerable:
    image: python:3.8-slim
    container_name: flask-vulnerable-container
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5001:5000"
    command: sh -c "pip install Flask==1.0.1 Jinja2==2.11.3 MarkupSafe==2.0.1 ItsDangerous==1.1.0 && python3 safe.py"
    #command: sh -c "pip install Flask==1.0.2 Jinja2==2.11.3 MarkupSafe==2.0.1 ItsDangerous==1.1.0 && python3 app.py"